name: forms

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  localization:
    path: ../localization


  # State management
  bloc: 8.1.0
  flutter_bloc: 8.1.1

  # Localization, font, icon
  localized_string: 0.2.0
  intl: 0.18.0

  # Atomic helper packages
  optional: 6.1.0+1
  decimal: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
