name: weather_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # Local packages
  forms:
    path: forms
  drivers:
    path: drivers
  localization:
    path: localization


  # Weather_app_configs
  #  ttm_app_config:
  #    git:
  #      url: https://github.com/ttm-keywallet/ttm-app-config
  #      ref: bc7b520b2088fe943e4bcd897fc60ab2e315ad86


  # Atomic helper packages
  equatable: 2.0.5
  optional: 6.1.0+1
  cryptography: 2.0.5
  collection: 1.17.0
  decimal: 2.2.0
  rational: 2.2.0
  uuid: 3.0.6
  encrypt: 5.0.1
  hex: 0.2.0
  base_codecs: 1.0.1


  # State management
  bloc: 8.1.0
  flutter_bloc: 8.1.1
  bloc_test: 9.1.0


  # Dependency injection
  get_it: 7.2.0


  # Api, connection, json serializer
  dio: 4.0.6
  json_annotation: any
  freezed_annotation: any


  # Plugins
  app_tracking_transparency: 2.0.2+4
  package_info_plus: 3.0.1

  # Localization, font, icon
  intl: 0.17.0
  cupertino_icons: 1.0.5
  crypto_font_icons: 1.0.1
  localized_string: 0.2.0


  # UI
  page_transition: 2.0.7
  qr_flutter: 4.0.0
  fluttertoast: 8.1.3
  simple_animations: 4.1.0
  styled_widget: 0.4.0+3
  overlay_support: 2.1.0
  flutter_svg: 1.1.6


  # Storages
  flutter_secure_storage: 5.0.2
  hive: 2.2.2
  hive_flutter: 1.1.0


  # Statistics and analytics
  firebase_core: 2.3.0
  firebase_messaging: 14.1.1
  firebase_crashlytics: 3.0.6


dev_dependencies:
  hive_test: ^1.0.1
  json_serializable: any
  mockito: 5.2.0

  build_runner: any
  freezed: any

  hive_generator: 1.1.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

