name: drivers
description: A new Flutter package.
version: 0.0.1
homepage: no page yet

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # workspace
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1

  localization:
    path: ../localization
  forms:
    path: ../forms
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: 8.1.0
  flutter_bloc: 8.1.1
  bloc_test: 9.1.0

  optional: 6.1.0+1
  decimal: 2.2.0
  rational: 2.2.0
  get_it: 7.2.0
  localized_string: 0.2.0

  dio: 4.0.6

  flutter_svg: 1.1.6
  encrypt: 5.0.1
  crypto: 3.0.2
  overlay_support: 2.1.0
  intl: 0.18.0

  firebase_core: 2.15.1
  firebase_messaging: 14.6.7
  firebase_crashlytics: 3.3.5

  hive: 2.2.2
  hive_flutter: 1.1.0

  path_provider: 2.1.0
  share_plus: 7.1.0

  connectivity_plus: 2.3.7
  cached_network_image: 3.2.1
  uuid: 3.0.7
  collection: 1.17.1

dev_dependencies:
  json_serializable: 6.7.1
  mockito: 5.4.2
  build_runner: 2.4.6
  freezed: 2.3.0

  hive_generator: 2.0.1
  flutter_test:
    sdk: flutter


#dependency_overrides:
#  file: 6.1.4
#  analyzer: 2.8.0
#  source_gen: 1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
