// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBabRFzVHYr8Afr7kGLEQbpQiYM9loclLk',
    appId: '1:281780045358:web:b29805d392d90985bcc1bf',
    messagingSenderId: '281780045358',
    projectId: 'weather-app-38184',
    authDomain: 'weather-app-38184.firebaseapp.com',
    storageBucket: 'weather-app-38184.appspot.com',
    measurementId: 'G-X904RBVRYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDOi62_axtoNm5VT21WQA9Ozvo2I4Fhk',
    appId: '1:281780045358:android:39dae96f9d99a447bcc1bf',
    messagingSenderId: '281780045358',
    projectId: 'weather-app-38184',
    storageBucket: 'weather-app-38184.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-LTteyKCwK-sPUBrBlwgi3R8fqiXd8nk',
    appId: '1:281780045358:ios:401a1791a3fa4e5bbcc1bf',
    messagingSenderId: '281780045358',
    projectId: 'weather-app-38184',
    storageBucket: 'weather-app-38184.appspot.com',
    iosClientId: '281780045358-98v4crldet8ah81f876nja2vd7pfq9rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-LTteyKCwK-sPUBrBlwgi3R8fqiXd8nk',
    appId: '1:281780045358:ios:401a1791a3fa4e5bbcc1bf',
    messagingSenderId: '281780045358',
    projectId: 'weather-app-38184',
    storageBucket: 'weather-app-38184.appspot.com',
    iosClientId: '281780045358-98v4crldet8ah81f876nja2vd7pfq9rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
